### ISSUE TITLE
Cost Benefit analysis

### ISSUE THREAD

**Issue by cboyer5** [cboyer5/IS436_group_project#1]
Create a CBA for the application

**Comment by cboyer5** [comment]
[COST-BENEFIT ANALYSIS.docx](https://github.com/cboyer5/IS436_group_project/files/12826442/COST-BENEFIT.ANALYSIS.docx)

**Comment by kaylaalam** [comment]
[COST-BENEFIT ANALYSIS (1).xlsx](https://github.com/cboyer5/IS436_group_project/files/12849398/COST-BENEFIT.ANALYSIS.1.xlsx)

**Comment by kaylaalam** [comment]
[COST-BENEFIT ANALYSIS (3).xlsx](https://github.com/cboyer5/IS436_group_project/files/12861456/COST-BENEFIT.ANALYSIS.3.xlsx)

UPDATED CBA
