### ISSUE TITLE
Construct use case diagrams and documents

### ISSUE THREAD

**Issue by cboyer5** [cboyer5/IS436_group_project#10]
create a minimum of 5 use cases that covers one or more functions in the functional requirements

**Comment by aobiora28** [comment]
[Use Case Documents and Diagrams.pdf](https://github.com/cboyer5/IS436_group_project/files/12920931/Use.Case.Documents.and.Diagrams.pdf)

**Comment by aobiora28** [comment]
[Use Case Documents and Diagrams.docx](https://github.com/cboyer5/IS436_group_project/files/12920939/Use.Case.Documents.and.Diagrams.docx)

**Comment by kaylaalam** [comment]
[Use.Case.Documents.and.Diagrams.docx](https://github.com/cboyer5/IS436_group_project/files/12921132/Use.Case.Documents.and.Diagrams.docx)
[Use.Case.Documents.and.Diagrams.pdf](https://github.com/cboyer5/IS436_group_project/files/12921131/Use.Case.Documents.and.Diagrams.pdf)

Updated this with the addition of the Use Case 2 diagram!
