### ISSUE TITLE
Personal Info needed for D3 Submission

### ISSUE THREAD

**Issue by cboyer5** [cboyer5/IS436_group_project#16]
Please fill out the requested info listed below. Feel free to use the template or to create your own bio.  Enter information in the comments below. 

contact information 
and short bios of the team members
role(s) they play in the project team.

**Sample:** 

Christine Boyer, cboyer5@umbc.edu
Bio: Christine is a senior in her last year of her IS degree. She has an interest in data science and machine learning. After graduation she plans to pursue a career in project management. 
Role on team: Project Manager

**Comment by jamzd223** [comment]
James Dennison, jamesd3@umbc.edu
Bio: James is a final-year undergraduate student at the University of Maryland, Baltimore County (UMBC), majoring in Information Systems. He's on track to earn both his Bachelor of Science in this discipline and a specialized Cybersecurity Informatics Certificate. Passionate about the world of digital defense, James possesses a keen interest in cybersecurity. As he approaches graduation, he aspires to transition into a role where he can leverage his knowledge and skills to fortify and protect digital assets in an ever-evolving technological landscape, with a particular focus on advancing modern cybersecurity practices and solutions.
Role on team: Technical Writer

**Comment by edwincarr1** [comment]
Edwin Carr, ecarr1@umbc.edu
Bio: Edwin is a fourth-year undergraduate student who attends the University of Maryland, Baltimore County, majoring in Information Systems. He has an interest in data science and Cloud Computing. Has experience with Data entry. Once graduated, he desires to go into a role where he can anchorage his comprehension meaning and expertise to help a business grow.
Role on team: Database Administrator

**Comment by kaylaalam** [comment]
Kayla Lam , klam9@umbc.edu

Bio: Kayla is a final-year undergraduate student at the University of Maryland, Baltimore County (UMBC), majoring in Information Systems. With a solid background in marketing and promotions within the music industry, she looks forward to applying her technical skills in combination with her passion for the field. After graduating, she aims to excel as a Marketing/Business Analyst, contributing her unique skill set to drive innovation and growth in the industry.

Role on team: Business Analyst

**Comment by aobiora28** [comment]
Afam Obiora, aobiora1@umbc.edu

Bio: Afam is a final-year undergraduate student at the University of Maryland, Baltimore County (UMBC), majoring in Information Systems. Deeply enthusiastic about Cybersecurity, InfoSec, and Information Technology with the academic background and practical experience to back it up.
With a foundation in database management , Information systems and cybersecurity fundamentals . He has honed his skills also making significant strides as a Cyber Operation Analyst, contributing to incident management and security alert analysis. His goal is to leverage his skills to enhance the security posture of organizations.

Role on team: Data Analyst

**Comment by yeahhsami** [comment]
Sami Kirmani, Samik1@umbc.edu

Bio: Sami is a final semester undergraduate student at the University of Maryland, Baltimore County, getting his Bachelor of Science in Information Systems. He has an interest in software development. Sami has experience with different disciplines within IT including, System administrator, Database management, and full-stack software development. After graduating he is looking for a software development role. 

Role on team: Software Developer
