### ISSUE TITLE
Write a system request

### ISSUE THREAD

**Issue by cboyer5** [cboyer5/IS436_group_project#2]
Write a system request which includes all of the required elements found here http://shivaprogramming.com/IS436/content/deliverable/d1.html

**Comment by jamzd223** [comment]
[System Request.docx](https://github.com/cboyer5/IS436_group_project/files/12841654/System.Request.docx)

[System Request.pdf](https://github.com/cboyer5/IS436_group_project/files/12841864/System.Request.pdf)
