### ISSUE TITLE
Construct ERD for Deliverable 4

### ISSUE THREAD

**Issue by cboyer5** [cboyer5/IS436_group_project#21]
Develop a data model by drawing an Entity-Relationship diagram using Visio, Lucid Charts (or any drawing tool) The model will be accompanied by a textual description of entities and relationships. The diagrams should closely follow the notation. Make sure that the model is in the third normal form.

- Take a look at Chapter 5 for reference

**Comment by jamzd223** [comment]
[ERD.pdf](https://github.com/cboyer5/IS436_group_project/files/13371032/ERD.pdf)
[Textual Description of Entities And Relationships.pdf](https://github.com/cboyer5/IS436_group_project/files/13371033/Textual.Description.of.Entities.And.Relationships.pdf)

**Comment by jamzd223** [comment]
[ERD.pdf](https://github.com/cboyer5/IS436_group_project/files/13371066/ERD.pdf)
[Textual Description of Entities And Relationships.pdf](https://github.com/cboyer5/IS436_group_project/files/13371067/Textual.Description.of.Entities.And.Relationships.pdf)

Also added both files to the "code" section
