### ISSUE TITLE
Write a feasibility Analysis

### ISSUE THREAD

**Issue by cboyer5** [cboyer5/IS436_group_project#3]
Construct a feasibility analysis that includes all of the required elements found here http://shivaprogramming.com/IS436/content/deliverable/d1.html

**Comment by aobiora28** [comment]
[Feasibility Analysis for Unicentral (A student academic based website).docx](https://github.com/cboyer5/IS436_group_project/files/12842224/Feasibility.Analysis.for.Unicentral.A.student.academic.based.website.docx)
