### ISSUE TITLE
Write a requirements definition document

### ISSUE THREAD

**Issue by cboyer5** [cboyer5/IS436_group_project#7]
write a requirements definition document which includes (1)functional and nonfunctional requirements. Functional requirements must be labeled as process-oriented or information-oriented; the non-functional requirements must be labeled as operational, performance, security or cultural/political.  (3) observation notes on the 'as-is' system.

**Comment by cboyer5** [comment]
https://docs.google.com/document/d/1QCfFXzmKwP4RLF4XF2Za_hTWkRyl08aWalTPxbILafc/edit?usp=sharing

**Comment by jamzd223** [comment]
Finalized documents:

[Observation Notes on the As-Is System.docx](https://github.com/cboyer5/IS436_group_project/files/12907894/Observation.Notes.on.the.As-Is.System.docx)
[Observation Notes on the As-Is System.pdf](https://github.com/cboyer5/IS436_group_project/files/12907895/Observation.Notes.on.the.As-Is.System.pdf)
[Requirements Definition Document.docx](https://github.com/cboyer5/IS436_group_project/files/12907896/Requirements.Definition.Document.docx)
[Requirements Definition Document.pdf](https://github.com/cboyer5/IS436_group_project/files/12907897/Requirements.Definition.Document.pdf)
